language: java
jdk:
  - oraclejdk9

before_script:
  - mkdir -p bin
  - export PATH=$PATH:$PWD/bin
  - wget http://build.berkeleybop.org/userContent/owltools/owltools -O bin/owltools
  - wget http://build.berkeleybop.org/userContent/owltools/ontology-release-runner -O bin/ontology-release-runner
  - wget http://build.berkeleybop.org/userContent/owltools/owltools-runner-all.jar -O bin/owltools-runner-all.jar
  - wget http://build.berkeleybop.org/userContent/owltools/owltools-oort-all.jar -O bin/owltools-oort-all.jar
  - wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot -O bin/robot
  - chmod +x bin/*
#  - wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot.jar -O bin/robot.jar
#  - wget http://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot -O bin/robot
#  - wget http://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot.jar -O bin/robot.jar


# command to run tests
script: cd src/ontology/ && make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - damion.dooley@bccdc.ca
