id: genepio
title: Genomic Epidemiology Ontology
github_org: GenEpiO
repo: genepio
release_artefacts:
  - base
  - full
  - simple
primary_release: full
import_group:
  annotation_properties:
        - rdfs:label
        - dc:description
        - dc:source
        - IAO:0000115
        - IAO:0000114
        - IAO:0000119
        - OBI:0001886
        - IAO:0000111
        - oboInOwl:hasAlternativeId
  products:
    - id: chebi
      module_type: filter
      base_iris:
        - http://purl.obolibrary.org/obo/genepio/imports/chebi_import.owl
    - id: doid
      module_type: filter
    - id: envo
      module_type: filter
    - id: foodon
      module_type: filter
    - id: ncbitaxon
      module_type: filter
    - id: obi
      module_type: filter
    - id: ro
      module_type: filter
    - id: uberon
      module_type: filter

    - id: general
      module_type: custom 

robot_java_args: '--xml-entities'