name: FORM - New Term Request
description: An issue form for submitting a new term request (NTR) for a class in GENEPIO
title: "NTR: [current term label]"
labels: ["term request"]
body:
  - type: input
    id: label
    attributes:
      label: Proposed Label
      description: The proposed label for the term. This should be as specific as required. If there is another ontology with the same label, but for a different definition consider reviewing the label. 
      placeholder: ex. bioinformatics pipeline name
    validations:
      required: true
  - type: input
    id: class
    attributes:
      label: Proposed Parent Class
      description: The parent class(es) for which this new term should be associated within the ontology.
      placeholder: ex. laboratory sequencing datum
    validations:
      required: true
  - type: textarea
    id: definition
    attributes: 
      label: Definition/Description
      description: Please provide brief description to help curators understand and differentiate your intended term.
      placeholder: ex. A laboratory sequencing datum which describes the name of the bioinformatics pipeline used.
    validations:
      required: true
  - type: input
    id: definition-source
    attributes: 
      label: Definition Source
      description: Any sources that contributed to the definition/description provided (e.g. a URL, identifier, ORCiD).
      placeholder: ex. https://en.wikipedia.org/wiki/<relevant page>
    validations:
      required: false
  - type: input
    id: alternative-labels
    attributes: 
      label: Alternative labels and/or synonyms
      description: Alternative labels should be used to indicate community- or context-specific labels, abbreviations, shorthand forms and the like. You can also indicate synonymy (e.g. broad, exact, narrow, or related).
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments (not an annotation)
      description: Other information or context you would like the curator(s) to know.
      placeholder: 
      value: 
    validations:
      required: false
  - type: input
    id: contributor
    attributes: 
      label: Optional - Contributor Attribution
      description: Your contributor information (ORCiD preferred) to add the term, within the ontology, if change(s) are accepted.
      placeholder: 0000-0001-5109-3700 or https://orcid.org/0000-0001-5109-3700
    validations:
      required: false

